variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  REQUIREMENTS: base

workflow:
  auto_cancel:
    on_new_commit: interruptible

default:
  image:
    name: "{{ cookiecutter.python_version }}"
    entrypoint: [""]

  cache:
    paths:
      - .cache/pip
      - venv/

stages:
  - test

test-lint:
  stage: test
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install tox
    - tox -p -e lint,types
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never

test-unittest:
  stage: test
  coverage: "/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install tox
    - tox -e unittest
  artifacts:
    when: always
    reports:
      junit: junitxml_report/report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "airflow/dags/common/**/*"
    - if: ($CI_COMMIT_BRANCH == "master")

test-validation:
  stage: test
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install tox
    - tox -e validation_tests
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: ($CI_COMMIT_BRANCH == "master")
